version: '2'

networks:
  pcxchg:

services:
  zookeeper0:
    container_name: zookeeper0
    extends:
      file: kafka.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - pcxchg

  zookeeper1:
    container_name: zookeeper1
    extends:
      file: kafka.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - pcxchg

  zookeeper2:
    container_name: zookeeper2
    extends:
      file: kafka.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - pcxchg

  kafka0:
    container_name: kafka0
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 9092:9092
    networks:
      - pcxchg

  kafka1:
    container_name: kafka1
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 10092:9092
    networks:
      - pcxchg

  kafka2:
    container_name: kafka2
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 11092:9092
    networks:
      - pcxchg

  kafka3:
    container_name: kafka3
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 12092:9092
    networks:
      - pcxchg

  orderer0.pcxchg.com:
    container_name: orderer0.pcxchg.com
    extends:
      file: orderer.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/pcxchg.com/orderers/orderer0.pcxchg.com/msp:/var/hyperledger/orderer/msp
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    networks:
      - pcxchg

  orderer1.pcxchg.com:
    container_name: orderer1.pcxchg.com
    extends:
      file: orderer.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/pcxchg.com/orderers/orderer1.pcxchg.com/msp:/var/hyperledger/orderer/msp
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    networks:
      - pcxchg

  orderer2.pcxchg.com:
    container_name: orderer2.pcxchg.com
    extends:
      file: orderer.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/pcxchg.com/orderers/orderer2.pcxchg.com/msp:/var/hyperledger/orderer/msp
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    networks:
      - pcxchg

  peer0.Asus.com:
    container_name: peer0.Asus.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.Asus.com
      - CORE_PEER_ADDRESS=peer0.Asus.com:7051
      - CORE_PEER_LOCALMSPID=AsusMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Asus.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Asus.com/peers/peer0.Asus.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer0.pcxchg.com
      - orderer1.pcxchg.com
      - orderer2.pcxchg.com
    networks:
      - pcxchg

  peer0.Dell.com:
    container_name: peer0.Dell.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.Dell.com
      - CORE_PEER_ADDRESS=peer0.Dell.com:7051
      - CORE_PEER_LOCALMSPID=DellMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Dell.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Dell.com/peers/peer0.Dell.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 10051:7051
      - 10053:7053
    depends_on:
      - orderer0.pcxchg.com
      - orderer1.pcxchg.com
      - orderer2.pcxchg.com
    networks:
      - pcxchg

  peer0.HP.com:
    container_name: peer0.HP.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.HP.com
      - CORE_PEER_ADDRESS=peer0.HP.com:7051
      - CORE_PEER_LOCALMSPID=HPMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.HP.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/HP.com/peers/peer0.HP.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 9051:7051
      - 9053:7053
    depends_on:
      - orderer0.pcxchg.com
      - orderer1.pcxchg.com
      - orderer2.pcxchg.com
    networks:
      - pcxchg

  peer0.Amazon.com:
    container_name: peer0.Amazon.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.Amazon.com
      - CORE_PEER_ADDRESS=peer0.Amazon.com:7051
      - CORE_PEER_LOCALMSPID=AmazonMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Amazon.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Amazon.com/peers/peer0.Amazon.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer0.pcxchg.com
      - orderer1.pcxchg.com
      - orderer2.pcxchg.com
    networks:
      - pcxchg

  cli.Asus:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Asus
    environment:
      - CORE_PEER_ID=cli.Asus.com
      - CORE_PEER_ADDRESS=peer0.Asus.com:7051
      - CORE_PEER_LOCALMSPID=AsusMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Asus.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/Asus.com:/etc/hyperledger/msp
    depends_on:
      - peer0.Asus.com
    networks:
      - pcxchg

  cli.Dell:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Dell
    environment:
      - CORE_PEER_ID=cli.Dell.com
      - CORE_PEER_ADDRESS=peer0.Dell.com:7051
      - CORE_PEER_LOCALMSPID=DellMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Dell.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/Dell.com:/etc/hyperledger/msp
    depends_on:
      - peer0.Dell.com
    networks:
      - pcxchg

  cli.HP:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.HP
    environment:
      - CORE_PEER_ID=cli.HP.com
      - CORE_PEER_ADDRESS=peer0.HP.com:7051
      - CORE_PEER_LOCALMSPID=HPMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@HP.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/HP.com:/etc/hyperledger/msp
    depends_on:
      - peer0.HP.com
    networks:
      - pcxchg

  cli.Amazon:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Amazon
    environment:
      - CORE_PEER_ID=cli.Amazon.com
      - CORE_PEER_ADDRESS=peer0.Amazon.com:7051
      - CORE_PEER_LOCALMSPID=AmazonMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Amazon.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/Amazon.com:/etc/hyperledger/msp
    depends_on:
      - peer0.Amazon.com
    networks:
      - pcxchg

  ca.Amazon:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca.Amazon
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/Amazon.com/ca/root/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.Amazon
    networks:
      - pcxchg

  ca.Asus:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca.Asus
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/Asus.com/ca/root/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.Asus
    networks:
      - pcxchg

  ca.Dell:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca.Dell
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/Dell.com/ca/root/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.Dell
    networks:
      - pcxchg

  ca.HP:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca.HP
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/HP.com/ca/root/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.HP
    networks:
      - pcxchg
